version: '2'

services:
  redis:
    image: redis:alpine
    container_name: redis_db
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
    restart: always
    networks:
      - redis_net

  rebrow:
    depends_on:
      - redis
    build: .
    container_name: rebrow
    ports:
      - 5001:5001
    links:
      - redis:redis
    restart: always
    networks:
      - redis_net

networks:
  redis_net:
    driver: bridge
